import type { Metadata } from 'next'
import Navbar from './components/Navbar'
import './ui/globals.css'
import { Box, ThemeProvider } from '@mui/material'
import mainTheme from './ui/theme'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'Pokedex App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ThemeProvider theme={mainTheme}>
      <html lang="en">
        <body>
          <Navbar />
          <Box>{children}</Box>
          <Footer />
        </body>
      </html>
    </ThemeProvider>
  )
}
